version: '3'

services:
  terrasort:
    volumes:
      - ./terrasort-volume:/app/result
    build:
      context: ./terrasort
      args:
        # profile, prod
        MODE: prod
    env_file: .env
