version: '3'

services:
  terrasort:
    build:
      context: ./terrasort
    image: jkulrativ/terrasort

    env_file: .env
  
  powergrid:
    build: ./powergrid
    image: jkulrativ/powergrid
    env_file: .env
