version: '3'

services:
  terrasort:
    build:
      context: ./terrasort
      args:
        # profile, prod
        MODE: prod
    env_file: .env
  
  powergrid:
    build: ./powergrid
    env_file: .env
